title: "Audio Annotation Tool"
description: "Annotate audio clips with transcriptions"
audio_folder: "https://storage.googleapis.com/audios-asr-cl"
max_history: 10
metadata_filename: "metadata.json"
whisper_model: "whisper-1"
transcription_language: "es"